Types:
    type: entity
    table: types
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
    oneToMany:
        products:
            targetEntity: Products
            mappedBy: type
    lifecycleCallbacks: {  }